apiVersion: v2
name: fides
version: 0.8.0
appVersion: "2.6.3"
description: Fides is an open-source privacy engineering platform for managing the fulfillment of data privacy requests in your runtime environment, and the enforcement of privacy regulations in your code.
type: application
keywords:
  - fides
  - fidesctl
  - fidesops
  - privacy
  - gdpr
  - ccpa
icon: https://raw.githubusercontent.com/ethyca/fides/main/docs/fides/docs/img/fides-logo.svg
home: https://fid.es
sources:
  - https://github.com/ethyca/fides
dependencies:
  - name: postgresql
    version: "12.1.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.deployPostgres
  - name: redis
    version: "17.6.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.deployRedis
