apiVersion: v2
name: fides
version: 0.16.1
appVersion: "2.48.1"
description: Fides is an open-source privacy engineering platform for managing the fulfillment of data privacy requests in your runtime environment, and the enforcement of privacy regulations in your code.
type: application
keywords:
  - fides
  - privacy
  - gdpr
  - ccpa
icon: https://raw.githubusercontent.com/ethyca/fides/main/docs/fides/docs/img/fides-logo.svg
home: https://fid.es
sources:
  - https://github.com/ethyca/fides
dependencies:
  - name: aws-load-balancer-controller
    version: "1.5.3"
    repository: "https://aws.github.io/eks-charts"
    condition: ingress.installIngressController.awsLoadBalancerController
  - name: postgresql
    version: "12.5.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.deployPostgres
  - name: redis
    version: "17.11.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.deployRedis
