apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fides.tomlConfigMapName" . }}
data:
  fides.toml: |
    [database]
    enabled = true

    [redis]
    enabled = true
    db_index = 0
    
    [security]
    cors_origins = {{ include "fides.corsOrigins" . | trim }}

    [execution]

    [root_user]

    [admin_ui]

    [notifications]
  celery.toml: |
    event_queue_prefix = "fides_worker"
    task_default_queue = "fides"
    task_always_eager = true