apiVersion: v1
kind: Service
metadata:
  name: {{ include "fides.fullname" . }}
  labels:
    {{- include "fides.labels" . | nindent 4 }}
  {{- with .Values.fides.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.fides.service.type }}
  ports:
    - port: {{ .Values.fides.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fides.fides.selectorLabels" . | nindent 4 }}
