{{- if .Values.fides.workers.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fides.worker.fullname" . }}
  labels:
    {{- include "fides.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fides.worker.selectorLabels" . | nindent 6 }}
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fides.worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fides.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: fides
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.fides.image.repository }}:{{ .Values.fides.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.fides.image.pullPolicy }}
          command: ["fides"]
          args: ["worker"]
          env:
            {{- include "fides.env" . | nindent 12 }}
          envFrom:
            - secretRef: 
                name: {{ include "fides.fidesSecuritySecretName" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
