apiVersion: v2
name: fides-minimal
version: 0.12.0
appVersion: "2.14.0"
description: Fides is an open-source privacy engineering platform for managing the fulfillment of data privacy requests in your runtime environment, and the enforcement of privacy regulations in your code. This version of the Helm chart removes some excess features such as the lookup function which may not be available in all cases, such as ArgoCD.
type: application
keywords:
  - fides
  - fidesctl
  - fidesops
  - privacy
  - gdpr
  - ccpa
icon: https://raw.githubusercontent.com/ethyca/fides/main/docs/fides/docs/img/fides-logo.svg
home: https://fid.es
sources:
  - https://github.com/ethyca/fides

