{{- if .Values.privacyCenter.enabled }}
{{- $volume := "config" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fides.privacyCenter.fullname" . }}
  labels:
    {{- include "fides.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fides.privacyCenter.selectorLabels" . | nindent 6 }}
  strategy: 
    {{- include "fides.deploymentStrategy" . | nindent 4 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fides.privacyCenter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fides.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: privacy-center
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.privacyCenter.image.repository }}:{{ .Values.privacyCenter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.privacyCenter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 24
            periodSeconds: 5
          volumeMounts:
          - name: {{ $volume }}
            mountPath: /app/config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ $volume }}
          configMap:
            name: {{ include "fides.privacyCenter.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
