{{- if .Values.privacyCenter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include  "fides.privacyCenter.fullname" . }}
  labels:
    {{- include "fides.labels" . | nindent 4 }}
spec:
  type: {{ .Values.privacyCenter.service.type }}
  ports:
    - port: {{ .Values.privacyCenter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fides.privacyCenter.selectorLabels" . | nindent 4 }}
{{- end }}
