name: cd
on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  release-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/setup-helm@v3
        id: helm-install
        with:
          version: 'v3.10.0'
      - name: Install chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          install_only: true
      - name: Package Charts
        run: cr package */
      - name: Release Charts
        run: cr upload --owner ethyca --git-repo fides-helm --skip-existing --token ${{ secrets.GITHUB_TOKEN }}