name: ci
on:
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  check-helm-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout-code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v3
        id: helm-install
        with:
          version: "v3.11.1"
      - name: Fides - Configure Helm
        id: helm-configure
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Lint Helm - Fides
        working-directory: ./fides/
        id: helm-lint
        run: helm lint
      - name: Fides - Check Helm Dependencies
        working-directory: ./fides/
        id: helm-dependency
        run: helm dependency build
